name: Tag on matching commit
description: Create a tag when a commit message contains a request to tag

inputs:
  github-token:
    description: Github Token for fetching Pull Request data
    required: true
    default: ${{ github.token }}
  push-tag:
    description: Push tag? (true/false)
    required: false
    default: 'false'
  tag-regex:
    description: Regex for validating tags
    required: false

outputs:
  tag:
    description: Detected tag
    value: ${{ steps.tag.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Fetch tag
      id: tag
      shell: python
      env:
        COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
        TAG_REGEX: ${{ inputs.tag-regex }}
      run: |-
        import os
        import re

        def set_output(k, v):
          s = f"::set-output name={k}::{v}"
          print("Set output:", s)
          print(s)

        def extract_tag(_pr_body, _tag_regex):
            tag_pattern = re.compile(r'\btag\s+(\S+)\b', re.IGNORECASE)  # This matches 'tag <word>'
            for line in _pr_body.splitlines():
                line = line.strip()

                # Search for all occurrences of "tag <word>"
                matches = tag_pattern.findall(line)

                # If there is more than one match, throw an error
                if len(matches) > 1:
                    raise ValueError(f"Multiple tags found in the same line: {line}")

                # If a tag is found, validate it with the regex and return it
                if matches:
                    tag = matches[0].strip()
                    if not _tag_regex or (_tag_regex and bool(re.match(_tag_regex, tag))):
                        return tag

            return None  # Return None if no tag is found

        tag_regex = os.getenv("TAG_REGEX", "")
        commit_message = os.getenv("COMMIT_MESSAGE", "")
        tag = None

        try:
            tag = extract_tag(commit_message, tag_regex)
            if tag:
                print("Tag detected:", tag)
                print(f"::notice title=Tag detected::The tag {tag} has been detected on the PR body.")
                set_output("tag", tag)
            else:
                print("No tag detected on PR body")
                print("::notice title=No tag detected::No tag has been detected on the PR body.")
        except ValueError as e:
            print(str(e))
            print("::error title=Multiple tags error::More than one tag found in the PR body.")
            exit(1)

    - name: Debug No PushTag
      if: steps.tag.outputs.tag && inputs.push-tag != 'true'
      shell: bash
      run: |-
        echo "Not pushing detected tag"
        echo "::notice title=Not pushing detected tag::A tag has been detected, but it will not be pushed"

    - name: Push tag
      if: steps.tag.outputs.tag && inputs.push-tag == 'true'
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ inputs.github-token }}
        tag: ${{ steps.tag.outputs.tag }}
